services:
  minecraft:
    image: ${IMAGE:-localhost/minecraft}:${TAG:-latest}
    ports:
      - "0.0.0.0:25565:25565"
    environment:
      EULA: "${EULA:-false}"
      DEBUG: "${DEBUG:-false}"
      JVM_OPTS: "${JAVA_OPTS:--Xms1G -Xmx2G}"
      SETTINGS_gamemode: "${GAMEMODE:-survival}"
      SETTINGS_hardcore: "${HARDCORE:-false}"
      SETTINGS_motd: "${MOTD:-A Minecraft Server}"
      SETTINGS_pvp: "${PVP:-true}"
